CREATE DATABASE FACEBOOK;
USE FACEBOOK;
CREATE TABLE ACCOUNTS(USERNAME VARCHAR(25),FIRSTNAME CHAR(50),POST INT,COUNTRY CHAR(50));
SELECT * FROM ACCOUNTS;
INSERT INTO ACCOUNTS VALUES("AMMU_123","ANITHA",7,"INDIA"),
("CHINNA REDDY_91","SRUYA",12,"INDIA"),
("_VARSHI_76","VARSHITHA",10,"KOREA"),
("GIRISHA_34","GIRISHA",5,"INDIA"),
("MALLI_41","MALLESWARI",8,"INDIA"),
("NAGASRI_AYINAM","NAGASRI",6,"US"),
("SUPRIYA_78","SUPRIYA",9,"US");

CREATE TABLE LIKES(USERNAME VARCHAR(50),LIKES INT,COMMENTS INT);
SELECT *FROM LIKES;
INSERT INTO LIKES VALUES("AMMU_123",40,40),
("CHINNA REDDY_91",100,100),("GIRISHA_34",89,78),("_VARSHI_76",67,99),("NAGASRI_AYINAM",0,0);

