USE FACEBOOK;
SELECT *FROM ACCOUNTS;
SELECT * FROM LIKES;
SELECT *FROM ACCOUNTS INNER JOIN LIKES ON ACCOUNTS.USERNAME=LIKES.USERNAME;

SELECT * FROM ACCOUNTS LEFT JOIN LIKES ON ACCOUNTS.USERNAME=LIKES.USERNAME;



SELECT DISTINCT ACCOUNTS.USERNAME,FIRSTNAME,POST,COUNTRY
FROM ACCOUNTS
INNER JOIN LIKES ON ACCOUNTS.USERNAME=LIKES.USERNAME;
SELECT ACCOUNTS 
SELECT ACCOUNTS FULL JOIN LIKES ON ACCOUNTS.USERNAME=LIKES.USERNAME;