CREATE DATABASE INSTAGRAM;
USE INSTAGRAM;
CREATE TABLE ACCOUNTS(USERNAME VARCHAR(255),FIRSTNAME CHAR(50),POST INT,COUNTRY CHAR(50));
SELECT *FROM ACCOUNTS;
INSERT INTO ACCOUNTS VALUES ("AMMU_123","ANITHA",7,"INDIA"),
("CHINNA REDDY_91","SRUYA",12,"INDIA"),
("_VARSHI_76","VARSHITHA",10,"KOREA"),
("GIRISHA_34","GIRISHA",5,"DUBAI"),
("MALLI_41","MALLESWARI",8,"PAKISTAN"),
("NAGASRI_AYINAM","NAGASRI",6,"SRILANKA"),
("SUPRIYA_78","SUPRIYA",9,"AFRICA");

CREATE TABLE LIKES(USERNAME VARCHAR(50),LIKES INT,COMMENTS INT);
SELECT *FROM LIKES
INSERT INTO LIKES VALUE("SURYA_91",100,100),
("ANITHA",99,99),
("_VARSHI_91",100,100),
("SUPPI_45",78,67),
("MALLI_MALLI",78,78),
("NAGA_45",3,34);