USE INSTAGRAM;
SELECT * FROM ACCOUNTS
WHERE POST>5 ORDER BY FIRSTNAME DESC;

SELECT COUNT(USERNAME),COUNTRY FROM ACCOUNTS GROUP BY COUNTRY;

SELECT MIN(POST),MAX(POST) FROM ACCOUNTS;



SELECT SUM(POST),AVG(POST) FROM ACCOUNTS;

SELECT *FROM ACCOUNTS;

SELECT COUNT(FIRSTNAME) FROM ACCOUNTS
HAVING COUNT(FIRSTNAME)>5;
SELECT COUNT(USERNAME),COUNTRY FROM ACCOUNTS 
GROUP BY COUNTRY HAVING COUNT(USERNAME)>1;






